In [ ]:
# Rubriks voor het notebook:
# Data handling 10%
# Visualisation and DAG 10%
# Correlation matrix and conclusions 10%
# Data prep for modelling 15%
# Algoritms and Models 10%
# Metrics and prediction 10%
# Markdown 15%
# Structure 10%
# Code 10%

# Algemeen

In [ ]:
# Dataframe check-in tijden: df_checkin
# Dataframe cardholders: df_cardholders

In [2]:
# Importeren benodigde libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
# CSV files inladen
df_CI_2017 = pd.read_csv('Check-in times\Check-in-times_sheet_2017-2018.csv', decimal='.')
df_CI_2018 = pd.read_csv('Check-in times\Check-in-times_sheet_2018-2019.csv', decimal='.')
df_CI_2019 = pd.read_csv('Check-in times\Check-in-times_sheet_2019-2020.csv', decimal='.')
df_CI_2020 = pd.read_csv('Check-in times\Check-in-times_sheet_2020-2021.csv', decimal='.')
df_CI_2021 = pd.read_csv('Check-in times\Check-in-times_sheet_2021- .csv', decimal='.')

df_MA_2020 = pd.read_csv('Cardholders\Membership Aclo_sheet_ACLO  2020-2021.csv', decimal='.')
df_MA_2021 = pd.read_csv('Cardholders\Membership Aclo_sheet_ACLO 2021-2022.csv', decimal='.')
df_MF_2020 = pd.read_csv('Cardholders\Membership Aclo_sheet_Fitness  2020-2021.csv', decimal='.')
df_MF_2021 = pd.read_csv('Cardholders\Membership Aclo_sheet_Fitness 2021-2022 .csv', decimal='.')

<>:2: SyntaxWarning: invalid escape sequence '\C'
<>:3: SyntaxWarning: invalid escape sequence '\C'
<>:4: SyntaxWarning: invalid escape sequence '\C'
<>:5: SyntaxWarning: invalid escape sequence '\C'
<>:6: SyntaxWarning: invalid escape sequence '\C'
<>:8: SyntaxWarning: invalid escape sequence '\M'
<>:9: SyntaxWarning: invalid escape sequence '\M'
<>:10: SyntaxWarning: invalid escape sequence '\M'
<>:11: SyntaxWarning: invalid escape sequence '\M'
<>:2: SyntaxWarning: invalid escape sequence '\C'
<>:3: SyntaxWarning: invalid escape sequence '\C'
<>:4: SyntaxWarning: invalid escape sequence '\C'
<>:5: SyntaxWarning: invalid escape sequence '\C'
<>:6: SyntaxWarning: invalid escape sequence '\C'
<>:8: SyntaxWarning: invalid escape sequence '\M'
<>:9: SyntaxWarning: invalid escape sequence '\M'
<>:10: SyntaxWarning: invalid escape sequence '\M'
<>:11: SyntaxWarning: invalid escape sequence '\M'
C:\Users\betti\AppData\Local\Temp\ipykernel_14780\541146343.py:2: SyntaxWarning: invalid escape sequence '\C'
  df_CI_2017 = pd.read_csv('Check-in times\Check-in-times_sheet_2017-2018.csv', decimal='.')
C:\Users\betti\AppData\Local\Temp\ipykernel_14780\541146343.py:3: SyntaxWarning: invalid escape sequence '\C'
  df_CI_2018 = pd.read_csv('Check-in times\Check-in-times_sheet_2018-2019.csv', decimal='.')
C:\Users\betti\AppData\Local\Temp\ipykernel_14780\541146343.py:4: SyntaxWarning: invalid escape sequence '\C'
  df_CI_2019 = pd.read_csv('Check-in times\Check-in-times_sheet_2019-2020.csv', decimal='.')
C:\Users\betti\AppData\Local\Temp\ipykernel_14780\541146343.py:5: SyntaxWarning: invalid escape sequence '\C'
  df_CI_2020 = pd.read_csv('Check-in times\Check-in-times_sheet_2020-2021.csv', decimal='.')
C:\Users\betti\AppData\Local\Temp\ipykernel_14780\541146343.py:6: SyntaxWarning: invalid escape sequence '\C'
  df_CI_2021 = pd.read_csv('Check-in times\Check-in-times_sheet_2021- .csv', decimal='.')
C:\Users\betti\AppData\Local\Temp\ipykernel_14780\541146343.py:8: SyntaxWarning: invalid escape sequence '\M'
  df_MA_2020 = pd.read_csv('Cardholders\Membership Aclo_sheet_ACLO  2020-2021.csv', decimal='.')
C:\Users\betti\AppData\Local\Temp\ipykernel_14780\541146343.py:9: SyntaxWarning: invalid escape sequence '\M'
  df_MA_2021 = pd.read_csv('Cardholders\Membership Aclo_sheet_ACLO 2021-2022.csv', decimal='.')
C:\Users\betti\AppData\Local\Temp\ipykernel_14780\541146343.py:10: SyntaxWarning: invalid escape sequence '\M'
  df_MF_2020 = pd.read_csv('Cardholders\Membership Aclo_sheet_Fitness  2020-2021.csv', decimal='.')
C:\Users\betti\AppData\Local\Temp\ipykernel_14780\541146343.py:11: SyntaxWarning: invalid escape sequence '\M'
  df_MF_2021 = pd.read_csv('Cardholders\Membership Aclo_sheet_Fitness 2021-2022 .csv', decimal='.')

# Data cleaning en verkenning van de data

## Check-in tijden

In [ ]:
# Hebben alle dataframes dezelfde kolommen?
df_CI_2017.head()

,Klant nr,Lid id,Geslacht,Abo bezoek,Incheckdatum
0,168236,Medewerker RUG,M,Fitness Card 2016-2017,2017-08-01 12:49:10
1,132339,RUG,M,Fitness Card 2016-2017,2017-08-01 12:53:11
2,141170,RUG,M,Fitness Card 2016-2017,2017-08-01 12:53:34
3,141170,RUG,M,Fitness Card 2016-2017,2017-08-01 12:54:13
4,186817,RUG,M,Fitness Card 2016-2017,2017-08-01 13:00:58

In [5]:
# In deze 'head' staan 2 regels voor klant 141170. Deze bezoeker is 2x ingecheckt binnen 1 minuut. -> Dit beschouwen als een dubbele regel? Meerdere van dit soort regels in de data?

In [6]:
df_CI_2018.head()

,Klant nr,Lid id,Geslacht,Abo bezoek,Incheckdatum
0,117879,Medewerker RUG/Hanze,M,Fitness Card 2017-2018,2018-08-01 12:48:52
1,146660,Medewerker RUG/Hanze,M,Fitness Card 2017-2018,2018-08-01 12:49:03
2,173963,Medewerker RUG/Hanze,M,Fitness Card 2017-2018,2018-08-01 12:54:52
3,185667,RUG,M,Fitness Card 2017-2018,2018-08-01 13:01:46
4,180476,Medewerker RUG/Hanze,M,Fitness Card 2017-2018,2018-08-01 13:03:11

In [7]:
df_CI_2019.head()

,Klant nr,Lid id,Geslacht,Abo bezoek,Incheckdatum
0,194261,RUG,M,Fitness 2nd semester Card 18-19,2019-08-02 12:48:58
1,186218,Hanze,M,Fitness Card 2018-2019,2019-08-02 12:50:31
2,186218,Hanze,M,Fitness Card 2018-2019,2019-08-02 12:50:35
3,202793,Hanze,M,Fitness Card 2018-2019,2019-08-02 12:51:29
4,114664,Medewerkers RUG/Hanze,M,SPR sportcard Incasso,2019-08-02 12:52:06

In [8]:
df_CI_2020.head()

,Klant nr,Lid id,Geslacht,Abo bezoek,Incheckdatum
0,204257,RUG,M,Fitness Card 2019-2020,2020-08-03 12:49:25
1,185550,Hanze,M,Fitness Card 2019-2020,2020-08-03 12:59:43
2,214192,RUG,M,Fitness Card 2019-2020,2020-08-03 14:16:11
3,172702,Hanze,M,Fitness Card 2019-2020,2020-08-03 14:16:22
4,202597,NaN,fout,NaN,2020-08-03 14:18:39

In [9]:
df_CI_2021.head()

   Klant nr      Lid id Geslacht Abo bezoek         Incheckdatum
0    189865  RUG               M        NaN  2021-08-02 13:00:10
1    223378  RUG               V        NaN  2021-08-02 13:00:15
2    220941  RUG               M        NaN  2021-08-02 13:00:20
3    159667  RUG               M        NaN  2021-08-02 13:00:27
4    212121  RUG               M        NaN  2021-08-02 13:00:32

In [10]:
# Kolomnamen in de Check-in-times zijn gelijk
# Kolomnamen omzetten naar lowercase en _ toevoegen tussen woorden
df_CI_2017.columns = df_CI_2017.columns.str.strip()
df_CI_2017.columns = df_CI_2017.columns.str.lower()
df_CI_2017.columns = df_CI_2017.columns.str.replace(" ", "_")

df_CI_2018.columns = df_CI_2018.columns.str.strip()
df_CI_2018.columns = df_CI_2018.columns.str.lower()
df_CI_2018.columns = df_CI_2018.columns.str.replace(" ", "_")

df_CI_2019.columns = df_CI_2019.columns.str.strip()
df_CI_2019.columns = df_CI_2019.columns.str.lower()
df_CI_2019.columns = df_CI_2019.columns.str.replace(" ", "_")

df_CI_2020.columns = df_CI_2020.columns.str.strip()
df_CI_2020.columns = df_CI_2020.columns.str.lower()
df_CI_2020.columns = df_CI_2020.columns.str.replace(" ", "_")

df_CI_2021.columns = df_CI_2021.columns.str.strip()
df_CI_2021.columns = df_CI_2021.columns.str.lower()
df_CI_2021.columns = df_CI_2021.columns.str.replace(" ", "_")

In [11]:
# Datum kolom omzetten naar een datetime object
df_CI_2017.incheckdatum = pd.to_datetime(df_CI_2017.incheckdatum)
df_CI_2018.incheckdatum = pd.to_datetime(df_CI_2018.incheckdatum)
df_CI_2019.incheckdatum = pd.to_datetime(df_CI_2019.incheckdatum)
df_CI_2020.incheckdatum = pd.to_datetime(df_CI_2020.incheckdatum)
df_CI_2021.incheckdatum = pd.to_datetime(df_CI_2021.incheckdatum)

In [12]:
# Datatypes check
df_CI_2017.dtypes

klant_nr                 int64
lid_id                  object
geslacht                object
abo_bezoek              object
incheckdatum    datetime64[ns]
dtype: object

In [13]:
df_CI_2018.dtypes

klant_nr                 int64
lid_id                  object
geslacht                object
abo_bezoek              object
incheckdatum    datetime64[ns]
dtype: object

In [14]:
df_CI_2019.dtypes

klant_nr                 int64
lid_id                  object
geslacht                object
abo_bezoek              object
incheckdatum    datetime64[ns]
dtype: object

In [15]:
df_CI_2020.dtypes

klant_nr                 int64
lid_id                  object
geslacht                object
abo_bezoek              object
incheckdatum    datetime64[ns]
dtype: object

In [16]:
df_CI_2021.dtypes

klant_nr                 int64
lid_id                  object
geslacht                object
abo_bezoek              object
incheckdatum    datetime64[ns]
dtype: object

In [17]:
# Check-in tijden samenvoegen tot 1 groot dataframe
# https://www.geeksforgeeks.org/pandas/how-to-merge-multiple-dataframes-in-pandas/ -> Optie 2: Concat
df_checkin = pd.concat([df_CI_2017, df_CI_2018, df_CI_2019, df_CI_2020, df_CI_2021], axis=0, join='outer', ignore_index=True)
df_checkin.head()

,klant_nr,lid_id,geslacht,abo_bezoek,incheckdatum
0,168236,Medewerker RUG,M,Fitness Card 2016-2017,2017-08-01 12:49:10
1,132339,RUG,M,Fitness Card 2016-2017,2017-08-01 12:53:11
2,141170,RUG,M,Fitness Card 2016-2017,2017-08-01 12:53:34
3,141170,RUG,M,Fitness Card 2016-2017,2017-08-01 12:54:13
4,186817,RUG,M,Fitness Card 2016-2017,2017-08-01 13:00:58

In [18]:
df_checkin.tail()

,klant_nr,lid_id,geslacht,abo_bezoek,incheckdatum
380780,152677,Hanze,V,Fitness howesp Card 21/22,2021-12-01 15:31:43
380781,209279,RUG,M,Fitness Card 2021/2022,2021-12-01 15:36:27
380782,210265,Medewerker RUG/Hanze,M,SPR sportcard Incasso,2021-12-01 15:37:56
380783,221819,RUG,V,Fitness Card 2021/2022,2021-12-01 15:38:36
380784,202478,Medewerker RUG/Hanze,M,SPR sportcard Incasso,2021-12-01 15:40:17

In [ ]:
# Unieke waarden tellen
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.value_counts.html
df_checkin.lid_id.value_counts(dropna=False)

lid_id
RUG                         157224
Hanze                        57741
NaN                          24953
RUG                          14734
RUG                          14374
                             ...
JEVA                             1
Medewerker RUG/Hanze ELO         1
BORUGI                           1
HanzeELE                         1
KAFA                             1
Name: count, Length: 119, dtype: int64

In [ ]:
# Spaties en andere ongewenste karakters verwijderen
# Prompt ChatGPT: In power BI heb je een functie om tekst te cleanen. Bepaalde onzichtbare karakters worden dan verwijderd. Heeft pandas ook een soortgelijke functie? Dan bedoel ik dus niet alleen het verwijderen van voorloop spaties.

df_checkin['lid_id'] = (
    df_checkin['lid_id']
    .str.replace('\xa0', ' ', regex=False)
    .str.replace(r'[\x00-\x1F\x7F]', '', regex=True)
    .str.strip()
)

In [ ]:
df_checkin['lid_id'].value_counts(dropna=False)

lid_id
RUG                         225749
Hanze                        84407
NaN                          24953
Medewerker RUG/Hanze         14848
Medewerker RUG                9552
                             ...
GORM                             1
Medewerker RUG/Hanze ELO         1
BORUGI                           1
HanzeELE                         1
KAFA                             1
Name: count, Length: 71, dtype: int64

In [37]:
df_checkin['geslacht'] = (
    df_checkin['geslacht']
    .str.replace('\xa0', ' ', regex=False)
    .str.replace(r'[\x00-\x1F\x7F]', '', regex=True)
    .str.strip()
)

In [39]:
df_checkin['geslacht'].value_counts(dropna=False)

geslacht
M       280767
V        83381
fout     16637
Name: count, dtype: int64

In [38]:
df_checkin['abo_bezoek'] = (
    df_checkin['abo_bezoek']
    .str.replace('\xa0', ' ', regex=False)
    .str.replace(r'[\x00-\x1F\x7F]', '', regex=True)
    .str.strip()
)

In [40]:
df_checkin['abo_bezoek'].value_counts(dropna=False)

abo_bezoek
Fitness Card 2017-2018              86417
Fitness Card 2018-2019              78229
Fitness Card 2019-2020              68943
SPR sportcard Incasso               26996
Fitness Card 2020-2021              14561
Fitness 2nd semester Card 18-19     12279
Fitness Card 2021/2022              11487
Fitness Midseason Card 2017-2018    10601
Fitness Free Card 2017-2018          8715
NaN                                  7774
Fitness 1st semester Card 19-20      7606
Fitness free Card 2018-2019          6633
Fitness free Card 2019-2020          5732
Fitness 2nd semester Card 19-20      4514
Fitness 1st semester Card 18-19      4401
ACLO Card 2021-2022                  3305
Fitness Card 2016-2017               3124
Fitness SPR                          2683
Fitness Summer Card 2017-2018        2163
Fitness ExchangeStud 2017-2018       2035
Fitness summer Card 2018-2019        1812
Fitness 1st semester 2021/2022       1761
Fitness 'krachtwacht' 2018-2019      1737
Fitness 1st semester 2020-2021       1145
Fitness prolong Card 2019-2020       1040
Fitness topsport Card 2018-2019       667
Fitness summer Card 2020-2021         659
Fitness Midseason Card 2016-2017      438
Fitness howesp Card 2019-2020         418
Fitness free Card 2020-2021           418
Fitness Summer Card 2016-2017         399
ACLO 1st semester Card 2021/2022      364
Fitness topsport Card 2019/2020       328
Fitness Free Card 2016-2017           278
Fitness free Card 21/22               249
Fitness howesp Card 2018-2019         234
Fitness topsport 2017-2018            192
Reitdiepkaart 2019-2020                91
Fitness howesp Card 21/22              91
Fitness howesp Card 2020-2021          60
SPR Free card                          54
ACLO free Card 2021/2022               45
Fitness prolong Card 2020-2021         32
Fitness summer Card 2019/2020          32
Fitness 2nd semester 2020-2021         17
Power Card 2016-2017                   11
Power Card NorthsideBB 2016-2017       11
Power Card 2017-2018                    2
Fitness topsport 2016-2017              2
Name: count, dtype: int64

### Categorieen samenvoegen/opschonen

#### lid_id

In [ ]:
df_checkin['lid_id'].value_counts(dropna=False)

lid_id
RUG                         225749
Hanze                        84407
NaN                          24953
Medewerker RUG/Hanze         14848
Medewerker RUG                9552
                             ...
GORM                             1
Medewerker RUG/Hanze ELO         1
BORUGI                           1
HanzeELE                         1
KAFA                             1
Name: count, Length: 71, dtype: int64

In [ ]:
# Extra kolom toevoegen om verder te bewerken
# https://www.statology.org/pandas-create-duplicate-column/
df_checkin['lid_id_standaard'] = df_checkin.loc[:, 'lid_id']
df_checkin.head()

,klant_nr,lid_id,geslacht,abo_bezoek,incheckdatum,lid_id_standaard
0,168236,Medewerker RUG,M,Fitness Card 2016-2017,2017-08-01 12:49:10,Medewerker RUG
1,132339,RUG,M,Fitness Card 2016-2017,2017-08-01 12:53:11,RUG
2,141170,RUG,M,Fitness Card 2016-2017,2017-08-01 12:53:34,RUG
3,141170,RUG,M,Fitness Card 2016-2017,2017-08-01 12:54:13,RUG
4,186817,RUG,M,Fitness Card 2016-2017,2017-08-01 13:00:58,RUG

In [ ]:
# Alle waarden die 'Medewerker' bevatten vervangen door 'Medewerker RUG/Hanze'
# Prompt ChatGPT: Ik heb een kolom die onder andere verschillende soorten medewerkers bevat. Ik wil in 1 keer alle waarden die 'Medewerker' bevatten vervangen door 'Medewerker'. Hoe doe ik dat in pandas?
df_checkin.loc[df_checkin['lid_id_standaard'].str.contains('Medewerker', na=False), 'lid_id_standaard'] = 'Medewerker RUG/Hanze'
df_checkin['lid_id_standaard'].value_counts(dropna=False)

lid_id_standaard
RUG                     225749
Hanze                    84407
Medewerker RUG/Hanze     33841
NaN                      24953
                          6431
- -        :  :           1855
-  -        :  :           742
WIWI                       337
VWIL                       286
BONI                       231
ETGE                       217
GEEJ                       190
-1-1 00  00:00:00          181
UIWI                       171
WITF                       164
RORA                       140
MEAD                       133
MORN                        81
OLTI                        63
DROK                        54
KILI                        52
LEFI                        47
HanzeEMC                    44
CAWO                        42
KRJN                        37
WACHanze                    37
-1-1900  00:00:00           32
MEJJ                        31
VALE                        29
TARI                        26
KLMO                        23
AJAA                        23
CRUGET                      21
DARA                        16
VEHanzeW                    15
waya                        10
WERUGW                      10
KLEB                         9
JEEU                         8
HanzeOHanzeO                 7
JENRUG                       7
BNAN                         7
VRJO                         4
RUGMEL                       4
-  -2       :  :             4
KAJA                         3
RUGCHanzeHanze               2
RUGAL_dili                   2
NAAU                         1
HanzeELE                     1
BORUGI                       1
A.KoRUGter@rug.nl            1
GORM                         1
JEVA                         1
KAFA                         1
Name: count, dtype: int64

In [ ]:
# Indelen in categorieen: RUG, Hanze, Medewerker RUG/Hanze, Overig/onbekend
# Promt ChatGPT: Ik heb nu een paar duidelijke hoofdcategorieën. Alles dat niet één van deze categorieën is, wil ik samenvoegen tot een categorie Overig/onbekend. Hoe doe ik dat in pandas?
categorie = ['RUG', 'Hanze', 'Medewerker RUG/Hanze']
df_checkin.loc[~df_checkin['lid_id_standaard'].isin(categorie), 'lid_id_standaard'] = 'Overig/Onbekend'

df_checkin['lid_id_standaard'].value_counts(dropna=False)

lid_id_standaard
RUG                     225749
Hanze                    84407
Overig/Onbekend          36788
Medewerker RUG/Hanze     33841
Name: count, dtype: int64

#### abo_bezoek

In [56]:
df_checkin['abo_bezoek'].value_counts(dropna=False)

abo_bezoek
Fitness Card 2017-2018              86417
Fitness Card 2018-2019              78229
Fitness Card 2019-2020              68943
SPR sportcard Incasso               26996
Fitness Card 2020-2021              14561
Fitness 2nd semester Card 18-19     12279
Fitness Card 2021/2022              11487
Fitness Midseason Card 2017-2018    10601
Fitness Free Card 2017-2018          8715
NaN                                  7774
Fitness 1st semester Card 19-20      7606
Fitness free Card 2018-2019          6633
Fitness free Card 2019-2020          5732
Fitness 2nd semester Card 19-20      4514
Fitness 1st semester Card 18-19      4401
ACLO Card 2021-2022                  3305
Fitness Card 2016-2017               3124
Fitness SPR                          2683
Fitness Summer Card 2017-2018        2163
Fitness ExchangeStud 2017-2018       2035
Fitness summer Card 2018-2019        1812
Fitness 1st semester 2021/2022       1761
Fitness 'krachtwacht' 2018-2019      1737
Fitness 1st semester 2020-2021       1145
Fitness prolong Card 2019-2020       1040
Fitness topsport Card 2018-2019       667
Fitness summer Card 2020-2021         659
Fitness Midseason Card 2016-2017      438
Fitness howesp Card 2019-2020         418
Fitness free Card 2020-2021           418
Fitness Summer Card 2016-2017         399
ACLO 1st semester Card 2021/2022      364
Fitness topsport Card 2019/2020       328
Fitness Free Card 2016-2017           278
Fitness free Card 21/22               249
Fitness howesp Card 2018-2019         234
Fitness topsport 2017-2018            192
Reitdiepkaart 2019-2020                91
Fitness howesp Card 21/22              91
Fitness howesp Card 2020-2021          60
SPR Free card                          54
ACLO free Card 2021/2022               45
Fitness prolong Card 2020-2021         32
Fitness summer Card 2019/2020          32
Fitness 2nd semester 2020-2021         17
Power Card 2016-2017                   11
Power Card NorthsideBB 2016-2017       11
Power Card 2017-2018                    2
Fitness topsport 2016-2017              2
Name: count, dtype: int64

In [57]:
# Extra kolom toevoegen om verder te bewerken
df_checkin['abo_bezoek_standaard'] = df_checkin.loc[:, 'abo_bezoek']
df_checkin.head()

,klant_nr,lid_id,geslacht,abo_bezoek,incheckdatum,lid_id_standaard,abo_bezoek_standaard
0,168236,Medewerker RUG,M,Fitness Card 2016-2017,2017-08-01 12:49:10,Medewerker RUG/Hanze,Fitness Card 2016-2017
1,132339,RUG,M,Fitness Card 2016-2017,2017-08-01 12:53:11,RUG,Fitness Card 2016-2017
2,141170,RUG,M,Fitness Card 2016-2017,2017-08-01 12:53:34,RUG,Fitness Card 2016-2017
3,141170,RUG,M,Fitness Card 2016-2017,2017-08-01 12:54:13,RUG,Fitness Card 2016-2017
4,186817,RUG,M,Fitness Card 2016-2017,2017-08-01 13:00:58,RUG,Fitness Card 2016-2017

In [62]:
# Jaartallen verwijderen uit abonnement
# Promt ChatGPT: Geef de regex voor het verwijderen van jaartallen in de vorm: 2021-2022
df_checkin['abo_bezoek_standaard'] = df_checkin['abo_bezoek_standaard'].str.replace(r'\d{4}-\d{4}', '', regex=True).str.strip()
df_checkin['abo_bezoek_standaard'] = df_checkin['abo_bezoek_standaard'].str.replace(r'\d{4}/\d{4}', '', regex=True).str.strip()
df_checkin['abo_bezoek_standaard'] = df_checkin['abo_bezoek_standaard'].str.replace(r'\d{2}-\d{2}', '', regex=True).str.strip()
df_checkin['abo_bezoek_standaard'] = df_checkin['abo_bezoek_standaard'].str.replace(r'\d{2}/\d{2}', '', regex=True).str.strip()
df_checkin['abo_bezoek_standaard'].value_counts(dropna=False)

abo_bezoek_standaard
Fitness Card                 262761
SPR sportcard Incasso         26996
Fitness 2nd semester Card     16793
Fitness free Card             13032
Fitness 1st semester Card     12007
Fitness Midseason Card        11039
Fitness Free Card              8993
NaN                            7774
ACLO Card                      3305
Fitness 1st semester           2906
Fitness SPR                    2683
Fitness Summer Card            2562
Fitness summer Card            2503
Fitness ExchangeStud           2035
Fitness 'krachtwacht'          1737
Fitness prolong Card           1072
Fitness topsport Card           995
Fitness howesp Card             803
ACLO 1st semester Card          364
Fitness topsport                194
Reitdiepkaart                    91
SPR Free card                    54
ACLO free Card                   45
Fitness 2nd semester             17
Power Card                       13
Power Card NorthsideBB           11
Name: count, dtype: int64

In [64]:
# Het woord 'Card' verwijderen
df_checkin['abo_bezoek_standaard'] = df_checkin['abo_bezoek_standaard'].str.replace('Card', '', regex=False).str.strip()
df_checkin['abo_bezoek_standaard'] = df_checkin['abo_bezoek_standaard'].str.replace('  ', ' ', regex=False).str.strip()
df_checkin['abo_bezoek_standaard'].value_counts(dropna=False)

abo_bezoek_standaard
Fitness                  262761
SPR sportcard Incasso     26996
Fitness 2nd semester      16810
Fitness 1st semester      14913
Fitness free              13032
Fitness Midseason         11039
Fitness Free               8993
NaN                        7774
ACLO                       3305
Fitness SPR                2683
Fitness Summer             2562
Fitness summer             2503
Fitness ExchangeStud       2035
Fitness 'krachtwacht'      1737
Fitness topsport           1189
Fitness prolong            1072
Fitness howesp              803
ACLO 1st semester           364
Reitdiepkaart                91
SPR Free card                54
ACLO free                    45
Power                        13
Power NorthsideBB            11
Name: count, dtype: int64

In [65]:
# Inconsistente spelling gelijktrekken
df_checkin['abo_bezoek_standaard'] = df_checkin['abo_bezoek_standaard'].str.replace('Fitness free', 'Fitness Free', regex=False).str.strip()
df_checkin['abo_bezoek_standaard'] = df_checkin['abo_bezoek_standaard'].str.replace('Fitness summer', 'Fitness Summer', regex=False).str.strip()
df_checkin['abo_bezoek_standaard'].value_counts(dropna=False)

abo_bezoek_standaard
Fitness                  262761
SPR sportcard Incasso     26996
Fitness Free              22025
Fitness 2nd semester      16810
Fitness 1st semester      14913
Fitness Midseason         11039
NaN                        7774
Fitness Summer             5065
ACLO                       3305
Fitness SPR                2683
Fitness ExchangeStud       2035
Fitness 'krachtwacht'      1737
Fitness topsport           1189
Fitness prolong            1072
Fitness howesp              803
ACLO 1st semester           364
Reitdiepkaart                91
SPR Free card                54
ACLO free                    45
Power                        13
Power NorthsideBB            11
Name: count, dtype: int64

In [ ]:
# Categorieen verder versimpelen?

## Dubbele check-ins

In [80]:
# Een check-in binnen 1 minuut wordt gezien als een dubbele regel
# Prompt ChatGPT: Ik heb een overzicht van check-in tijden van een sportschool. Ik wil regels van dezelfde klant markeren als mogelijke dubbele regel als zij binnen 1 minuut nog een keer inchecken. Hoe doe ik dit in pandas.

# Sorteren op klant en tijd
df_checkin = df_checkin.sort_values(['klant_nr', 'incheckdatum'])

# Vorige check-in van dezelfde klant ophalen
df_checkin['vorige_checkin'] = (df_checkin.groupby('klant_nr')['incheckdatum'].shift(1))

# Tijdsverschil in seconden berekenen
df_checkin['verschil_seconden'] = (df_checkin['incheckdatum'] - df_checkin['vorige_checkin']).dt.total_seconds()

# Mogelijk duplicaat markeren (< 60 seconden)
df_checkin['mogelijk_duplicaat'] = (df_checkin['verschil_seconden'] < 60)
# df_checkin['mogelijk_duplicaat'] = (df_checkin['verschil_seconden'] < 120)
# df_checkin['mogelijk_duplicaat'] = (df_checkin['verschil_seconden'] < 300)

df_checkin = df_checkin.sort_values(['incheckdatum'])
df_checkin.head()

,klant_nr,lid_id,geslacht,abo_bezoek,incheckdatum,lid_id_standaard,abo_bezoek_standaard,vorige_checkin,verschil_seconden,mogelijk_duplicaat
0,168236,Medewerker RUG,M,Fitness Card 2016-2017,2017-08-01 12:49:10,Medewerker RUG/Hanze,Fitness,NaT,NaN,False
1,132339,RUG,M,Fitness Card 2016-2017,2017-08-01 12:53:11,RUG,Fitness,NaT,NaN,False
2,141170,RUG,M,Fitness Card 2016-2017,2017-08-01 12:53:34,RUG,Fitness,NaT,NaN,False
3,141170,RUG,M,Fitness Card 2016-2017,2017-08-01 12:54:13,RUG,Fitness,2017-08-01 12:53:34,39.0,True
4,186817,RUG,M,Fitness Card 2016-2017,2017-08-01 13:00:58,RUG,Fitness,NaT,NaN,False

In [81]:
df_checkin['mogelijk_duplicaat'].value_counts(dropna=False)

mogelijk_duplicaat
False    336804
True      43981
Name: count, dtype: int64

## Card holders

In [82]:
# Dezelfde kolommen?
df_MA_2020.head()

   Klant nr Geslacht Man Geslacht vrouw         Omschrijving
0    206602          NaN          Vrouw  ACLO Card 2020-2021
1    220965          NaN          Vrouw  ACLO Card 2020-2021
2    221004          Man            NaN  ACLO Card 2020-2021
3    200011          Man            NaN  ACLO Card 2020-2021
4    187611          Man            NaN  ACLO Card 2020-2021

In [83]:
df_MA_2021.head()

   Klant nr Geslacht Man Geslacht vrouw         Omschrijving
0    179077          Man            NaN  ACLO Card 2021-2022
1    186113          Man            NaN  ACLO Card 2021-2022
2    228030          NaN          Vrouw  ACLO Card 2021-2022
3    228066          Man            NaN  ACLO Card 2021-2022
4    227911          NaN          Vrouw  ACLO Card 2021-2022

In [84]:
df_MF_2020.head()

   Klant nr Geslacht Man Geslacht vrouw            Omschrijving
0    220826          Man            NaN  Fitness Card 2020-2021
1    214958          Man            NaN  Fitness Card 2020-2021
2    220988          Man            NaN  Fitness Card 2020-2021
3    220843          NaN          Vrouw  Fitness Card 2020-2021
4    209275          Man            NaN  Fitness Card 2020-2021

In [85]:
df_MF_2021.head()

   Klant nr Geslacht Man Geslacht vrouw            Omschrijving
0    226676          NaN          Vrouw  Fitness Card 2021/2022
1    228069          NaN          Vrouw  Fitness Card 2021/2022
2    227923          Man            NaN  Fitness Card 2021/2022
3    227950          NaN          Vrouw  Fitness Card 2021/2022
4    228116          Man            NaN  Fitness Card 2021/2022

In [86]:
# Kolomnamen omzetten naar lowercase en _ toevoegen tussen woorden
df_MA_2020.columns = df_MA_2020.columns.str.strip()
df_MA_2020.columns = df_MA_2020.columns.str.lower()
df_MA_2020.columns = df_MA_2020.columns.str.replace(" ", "_")

df_MA_2021.columns = df_MA_2021.columns.str.strip()
df_MA_2021.columns = df_MA_2021.columns.str.lower()
df_MA_2021.columns = df_MA_2021.columns.str.replace(" ", "_")

df_MF_2020.columns = df_MF_2020.columns.str.strip()
df_MF_2020.columns = df_MF_2020.columns.str.lower() 
df_MF_2020.columns = df_MF_2020.columns.str.replace(" ", "_")

df_MF_2021.columns = df_MF_2021.columns.str.strip()
df_MF_2021.columns = df_MF_2021.columns.str.lower()     
df_MF_2021.columns = df_MF_2021.columns.str.replace(" ", "_")

In [87]:
# Datatypes check
df_MA_2020.dtypes

klant_nr           int64
geslacht_man      object
geslacht_vrouw    object
omschrijving      object
dtype: object

In [88]:
df_MA_2021.dtypes

klant_nr           int64
geslacht_man      object
geslacht_vrouw    object
omschrijving      object
dtype: object

In [89]:
df_MF_2020.dtypes

klant_nr           int64
geslacht_man      object
geslacht_vrouw    object
omschrijving      object
dtype: object

In [90]:
df_MF_2021.dtypes

klant_nr           int64
geslacht_man      object
geslacht_vrouw    object
omschrijving      object
dtype: object

In [91]:
# Cardholders samenvoegen tot 1 groot dataframe
# https://www.geeksforgeeks.org/pandas/how-to-merge-multiple-dataframes-in-pandas/ -> Optie 2: Concat
df_cardholders = pd.concat([df_MA_2020, df_MA_2021, df_MF_2020, df_MF_2021], axis=0, join='outer', ignore_index=True)
df_cardholders.head()

   klant_nr geslacht_man geslacht_vrouw         omschrijving
0    206602          NaN          Vrouw  ACLO Card 2020-2021
1    220965          NaN          Vrouw  ACLO Card 2020-2021
2    221004          Man            NaN  ACLO Card 2020-2021
3    200011          Man            NaN  ACLO Card 2020-2021
4    187611          Man            NaN  ACLO Card 2020-2021

In [92]:
df_cardholders.tail()

       klant_nr geslacht_man geslacht_vrouw            omschrijving
32825    231111          Man            NaN  Fitness Card 2021/2022
32826    234974          Man            NaN  Fitness Card 2021/2022
32827    232465          NaN          Vrouw  Fitness Card 2021/2022
32828    235592          Man            NaN  Fitness Card 2021/2022
32829    235449          Man            NaN  Fitness Card 2021/2022

In [93]:
# Strings cleanen 
df_cardholders['geslacht_man'] = (
    df_cardholders['geslacht_man']
    .str.replace('\xa0', ' ', regex=False)
    .str.replace(r'[\x00-\x1F\x7F]', '', regex=True)
    .str.strip()
)

df_cardholders['geslacht_vrouw'] = (
    df_cardholders['geslacht_vrouw']
    .str.replace('\xa0', ' ', regex=False)
    .str.replace(r'[\x00-\x1F\x7F]', '', regex=True)
    .str.strip()
)

df_cardholders['omschrijving'] = (
    df_cardholders['omschrijving']
    .str.replace('\xa0', ' ', regex=False)
    .str.replace(r'[\x00-\x1F\x7F]', '', regex=True)
    .str.strip()
)

In [ ]:
# 1 kolom geslacht maken
# Prompt ChatGPT: Ik heb een kolom geslacht_man en een kolom geslacht_vrouw. Ik wil hier 1 nieuwe kolom van maken. Als de kolom man en de kolom vrouw beide zijn gevuld dan is het geslacht onbekend. 
# Als de kolom man is gevuld is het een man, als de kolom vrouw is gevuld is het een vrouw. Als beide kolommen leeg zijn is het geslacht onbekend. Hoe doe ik dit in pandas?
# Vervolgvraag: Gebruik apply()  

def bepaal_geslacht(row):
    man = pd.notna(row['geslacht_man']) and str(row['geslacht_man']).strip() != ''
    vrouw = pd.notna(row['geslacht_vrouw']) and str(row['geslacht_vrouw']).strip() != ''

    if man and not vrouw:
        return 'Man'
    elif vrouw and not man:
        return 'Vrouw'
    else:
        return 'Onbekend'


df_cardholders['geslacht'] = df_cardholders.apply(bepaal_geslacht, axis=1)
df_cardholders.head()

   klant_nr geslacht_man geslacht_vrouw         omschrijving geslacht
0    206602          NaN          Vrouw  ACLO Card 2020-2021    Vrouw
1    220965          NaN          Vrouw  ACLO Card 2020-2021    Vrouw
2    221004          Man            NaN  ACLO Card 2020-2021      Man
3    200011          Man            NaN  ACLO Card 2020-2021      Man
4    187611          Man            NaN  ACLO Card 2020-2021      Man

In [103]:
df_cardholders.geslacht.value_counts(dropna=False)

geslacht
Vrouw       17119
Man         14903
Onbekend      808
Name: count, dtype: int64

In [102]:
df_cardholders.omschrijving.value_counts(dropna=False)

omschrijving
ACLO Card 2021-2022       16523
ACLO Card 2020-2021       13952
Fitness Card 2021-2022     1371
Fitness Card 2020-2021      984
Name: count, dtype: int64

In [100]:
# Spelling gelijktrekken
df_cardholders['omschrijving'] = df_cardholders['omschrijving'].str.replace('2021/2022', '2021-2022', regex=False)
df_cardholders.omschrijving.value_counts(dropna=False)

omschrijving
ACLO Card 2021-2022       16523
ACLO Card 2020-2021       13952
Fitness Card 2021-2022     1371
Fitness Card 2020-2021      984
Name: count, dtype: int64

In [ ]:
# Het jaartal scheiden van het abonnementstype, beide waarden in een aparte kolom zetten

In [ ]:
# Dubbele regels markeren

In [ ]:
# Het moet misschien toch anders. Dataframe maken met alle ACLO Card houders, in een aparte kolom zetten of deze leden ook een Fitness card hebben.

# Descriptive statistics en basis visualisaties

In [ ]:
# Descriptive statistics en visualisaties:
# - Man/vrouw verhouding
# - Aantal bezoekers per dag -> Is dit een statistic van deze data of van een transformatie? -> Verdere statistics hiervan?
# - Type leden (lid_id), welke categorieen en aantallen
# - Type abonnementen (abo_bezoek), welke categorieen en aantallen
# - Aantallen per dag van de week
# - Aantallen per week (weeknummer)
# - Aantallen per maand
# - Totalen per jaar
# - Lijngrafiek bezoekers in de loop van de tijd/tijdlijn (per dag, week, maand of jaar?)

## Check-in tijden

## Card holders

# Model

## DAG

In [ ]:
# Mogelijke verbanden:
# Geslacht heeft invloed op het aantal bezoekers -> meer mannen dan vrouwen in de fitness data
# Er gaan meer studenten dan medewerkers naar de fitness?
# Op bepaalde dagen gaan er meer mensen naar de fitness, in het weekend zijn studenten bij hun ouders, dus dan minder bezoekers
# In de vakanties zijn er minder bezoekers
# In de tentamenweken zijn er minder bezoekers
# In de zomer minder bezoekers dan in de winter? Invloed van het seizoen
# In bepaalde maanden meer of minder bezoekers
# Vanaf een bepaalde datum was het toegestaan dat ACLO card houders op bepaalde dagen toegang hebben tot de fitness. Maar het is nog steeds waarschijnlijker dat fitness card houders meer naar de fitness gaan.
# Datum bepaalt welke maand/dag/week/seizoen het is, of het tentamenperiode is of niet
# Tentamenperiodes hebben wel invloed op bezoeken van studenten, maar niet op dat van medewerkers
# Of het weekend is heeft meer invloed op de bezoeken van studenten dan dat van medewerkers

# Extra:
# Weersinvloeden
# Corona maatregelen

## Correlaties